// Maps story IDs to their scene module file name
const storyToSceneFile = {
  'monkey-and-crocodile': 'monkey-crocodile',
  'tortoise-and-geese': 'tortoise-geese',
  'blue-jackal': 'blue-jackal',
  'lion-and-rabbit': 'lion-rabbit',
  'loyal-mongoose': 'loyal-mongoose',
  'crow-and-snake': 'crow-snake',
  'musical-donkey': 'musical-donkey',
  'monkey-and-wedge': 'monkey-wedge',
  'jackal-and-drum': 'jackal-drum',
  'talking-cave': 'talking-cave',
  'three-fish': 'three-fish',
  'brahmin-dream': 'brahmin-dream',
  'elephant-and-mice': 'elephant-mice',
  'krishna-butter': 'krishna-butter',
  'chhota-bheem': 'chhota-bheem',
  'odysseus-troy': 'troy',
  'motu-patlu': 'motu-patlu',
  'two-headed-bird': 'two-headed-bird',
  'stork-and-crab': 'stork-crab',
  'hanuman-sun': 'hanuman-sun',
  'ganesha-moon': 'ganesha-moon',
  'prahlad-faith': 'prahlad',
  'shinchan-homework': 'shinchan',
  'doraemon-gadget': 'doraemon',
  'hercules-apples': 'hercules',
  'icarus-wings': 'icarus',
  'krishna-govardhan': 'krishna-govardhan',
  'krishna-kaliya': 'krishna-kaliya',
  'krishna-fruit-seller': 'krishna-fruit',
  'bheem-kirmada': 'bheem-kirmada',
  'oggy-adventure': 'oggy',
};

export default storyToSceneFile;
